hello-service:
  replicas: 3
  image:
    name: hello-service
    tag: t2020-06-15-598a2ca
  envFrom:
    envConfigEnabled: false
  service:
    enabled: false
  health:
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 60
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 60