hello-service:
  replicas: 2
  image:
    name: hello-service
    tag: t2020-06-16-885fdc6
  envFrom:
    envConfigEnabled: false
  service:
    enabled: false
  health:
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5