hello-service:
  replicas: 1
  image:
    name: hello-service
    tag: 2020-05-19-051101edf5f9b0fc249971afdca64d8e89bb9e91
  envFrom:
    envConfigEnabled: false
  service:
    enabled: false
  health:
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 60
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 60