hello-service:
  replicas: 1
  image:
    name: hello-service
    tag: 2020-05-18-4df37da
  envFrom:
    envConfigEnabled: false
  service:
    enabled: false
  health:
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 60
    readinessProbe:
      httpGet:
        path: /
        port: 8080
    initialDelaySeconds: 60