test-service:
  replicas: 2
  image:
    name: test-service
    tag: t2020-08-01-c7d6149
  envFrom:
    envConfigEnabled: false
  service:
    enabled: false
  health:
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5