hello-service:
  replicas: 2
  image:
    name: hello-service
    tag: version-t2020-07-31-f8b8c7e
  envFrom:
    envConfigEnabled: false
  service:
    enabled: false
  health:
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5