hello-service:
  replicas: 2
  image:
    name: hello-service
    tag: t2020-10-23-64202d6
  envFrom:
    envConfigEnabled: false
  service:
    enabled: false
  serviceMonitor:
    enabled: false    
  health:
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
