on:
  repository_dispatch:
    types: [deploy]
name: deploy
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.CI_TOKEN }}
    - name: Turnstyle
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}          
  tag:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.CI_TOKEN }}
          fetch-depth: 2
    - run: |
        git checkout HEAD^
        sed -i 's/tag.*/tag: ${{ github.event.client_payload.tag }}/g' ${{ github.event.client_payload.service }}/k8s/values.yaml
        git status
        git add ${{ github.event.client_payload.service }}/k8s/.
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Auto update ${{ github.event.client_payload.service }} tag:${{ github.event.client_payload.tag }}"
        git push

