on:
  repository_dispatch:
    types: [my-event]
name: deploy
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Turnstyle
      uses: softprops/turnstyle@v1
      with:  
        continue-after-seconds: 180         
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}    
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.CI_TOKEN }}
    - name: Change the deployment tag on master
      if: github.ref == 'refs/heads/master'
      run: |
        sed -i 's/tag.*/tag: ${{ github.event.client_payload.tag }}/g' ${{ github.event.client_payload.service }}/k8s/values.yaml
        git status
        git add test_service/k8s/.
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Auto update ${{ github.event.client_payload.service }} tag:${{ github.event.client_payload.tag }}"
    - name: Push changes to master
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.CI_TOKEN }} 
