on:
  issue_comment:
    types: [created]
name: Hello-Service CI 
jobs:
  merged:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '#deploy-hello-service')
    runs-on: ubuntu-latest
    outputs:
      ecr: ${{ steps.login-ecr.outputs.registry }}
      data: ${{steps.date.outputs.date}}
      commit: ${{steps.commit.outputs.short}}
      branch: ${{steps.branch.outputs.branch}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-2
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%F')"
    - name: Get short commit
      id: commit
      run: echo "::set-output name=short::$(git rev-parse --short HEAD)"
    - name: Get branch name
      id: branch
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
  
  build:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.build.outputs.tag }}
    needs: merged
    steps:      
    - name: Build image
      id: build
      env:
        REPO: test-go
        SERVICE_NAME: hello-service
        LATEST_TAG: latest
        TAG: ${{needs.merged.outputs.date}}-${{needs.merged.outputs.commit}}
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        BRANCH: ${{needs.merged.outputs.branch}}
        COMMIT: ${{needs.merged.outputs.commit}}
        ECR_REGISTRY: ${{ needs.merged.outputs.ecr }}
      run: |
        # Build and tag a docker image
        docker build --no-cache --build-arg GITHUB_TOKEN --build-arg REPO=${REPO} --build-arg BRANCH=${BRANCH} --build-arg COMMIT=${COMMIT} -t $ECR_REGISTRY/$SERVICE_NAME:$LATEST_TAG \
                                              -t $ECR_REGISTRY/$SERVICE_NAME:$TAG hello_service/.
        echo "::set-output name=tag::$TAG"
        echo "::set-output name=service::$SERVICE_NAME"
        echo "::set-output name=image::$ECR_REGISTRY/$SERVICE_NAME:$TAG"
        echo "::set-output name=latest-tag::$ECR_REGISTRY/$SERVICE_NAME:$LATEST_TAG"
    # - name: Scan image
    #   id: scan-image
    #   uses: anchore/scan-action@master
    #   with:
    #     image-reference: ${{ steps.build.outputs.image }}
    #     fail-build: true      
    - name: Push image
      id: push     
      run: |
        # push docker image to ECR
        docker push ${{ steps.build.outputs.image }}
        docker push ${{ steps.build.outputs.latest-tag }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:          
    - name: Change the image tag
      run: |
        #change the tag to the new one on values.yaml
        sed -i 's/tag.*/tag: ${{ needs.build.outputs.tag }}/g' hello_service/k8s-hello-service/values.yaml
    - name: Check for changes
      run: git status
    - name: Commit changed files

      run: |
        git add hello_service/k8s-hello-service/.
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Auto updating image tag:${{ needs.build.outputs.tag }}"
    - name: Push changes
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.CI_TOKEN }}