on:
  push:
    paths:
      - 'hello_service/**'
      - '!hello_service/k8s/**'
      - '!hello_service/k8s-external/**'
      - 'scripts/**'
name: hello-service 
jobs:
  check:
    runs-on: ubuntu-latest
    # needs: go
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.CI_TOKEN }}
    - name: Turnstyle
      uses: softprops/turnstyle@v1
      with:
        same-branch-only: false
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
  info:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.CI_TOKEN }}
    - name: Git info
      id: git
      run: |
        SERVICE_NAME=hello-service
        REPO=$(pwd | awk -F / '{print $(NF -1)}')
        SERVICE_PATH=hello_service
        BRANCH=$(git branch | grep \* | cut -d ' ' -f2)
        BRANCH_PREFIX=$(git branch | grep \* | cut -d ' ' -f2 | cut -d '/' -f1)
        COMMIT=$(git rev-parse --short HEAD)
        echo "::set-output name=service::$SERVICE_NAME"
        echo "::set-output name=repo::$REPO"
        echo "::set-output name=path::$SERVICE_PATH"
        echo "::set-output name=branch::$BRANCH"
        echo "::set-output name=prefix::$BRANCH"
        echo "::set-output name=commit::$COMMIT"
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.CI_TOKEN }}
        event-type: build
        build-payload: '{"service": "${{ steps.git.outputs.service }}", "repo": "${{ steps.git.outputs.repo }}", "path": "${{ steps.git.outputs.path }}", "branch": "${{ steps.git.outputs.branch }}", "prefix": "${{ steps.git.outputs.prefix }}", "commit": "${{ steps.git.outputs.commit }}"}'
