on:
  push:
    paths:
      - 'hello_service/**'
      - '!hello_service/k8s/**'
      - '!hello_service/k8s-external/**'
      - 'scripts/**'
          
name: hello-service 
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.CI_TOKEN }}
    - name: Turnstyle
      uses: softprops/turnstyle@v1
      with:  
        continue-after-seconds: 180
        same-branch-only: false
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}       
    - name: Git info
      id: git
      run: |
        REPO=$(pwd | awk -F / '{print $(NF -1)}')
        BRANCH=$(git branch | grep \* | cut -d ' ' -f2)
        BRANCH_PREFIX=$(git branch | grep \* | cut -d ' ' -f2 | cut -d '/' -f1)
        COMMIT=$(git rev-parse --short HEAD)
        echo "::set-output name=repo::$REPO"
        echo "::set-output name=branch::$BRANCH"
        echo "::set-output name=prefix::$BRANCH_PREFIX"
        echo "::set-output name=commit::$COMMIT"                    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-2
    - name: Build image
      id: build
      env:
        SERVICE_NAME: hello-service 
        REPO: ${{ steps.git.outputs.repo }}
        BRANCH: ${{ steps.git.outputs.branch }}
        BRANCH_PREFIX: ${{ steps.git.outputs.prefix }}
        COMMIT: ${{ steps.git.outputs.commit }}
        ECR: ${{ steps.login-ecr.outputs.registry }}
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      run: |
       # Create a tag for docker image 
        if [[ $BRANCH_PREFIX != "master" ]]; then
          TAG=${BRANCH_PREFIX}-t$(date "+%F")-${{ steps.git.outputs.commit }}
          LATEST_TAG=${BRANCH_PREFIX}-latest
        else
          TAG=t$(date "+%F")-${{ steps.git.outputs.commit }}
          LATEST_TAG=latest  
        fi
        # Build a docker image
        docker build --no-cache --build-arg GITHUB_TOKEN  --build-arg REPO=${REPO} --build-arg BRANCH=${BRANCH} --build-arg COMMIT=${COMMIT} -t $ECR/$SERVICE_NAME:$LATEST_TAG \
                                              -t $ECR/$SERVICE_NAME:$TAG hello_service/.
        echo "::set-output name=service::hello_service"
        echo "::set-output name=tag::$TAG"
        echo "::set-output name=latest::$LATEST_TAG"
        echo "::set-output name=image::$ECR/$SERVICE_NAME"
        echo "::set-output name=deploy::kubectl set image deployment/dev-$SERVICE_NAME-$SERVICE_NAME $SERVICE_NAME=$ECR/$SERVICE_NAME:$TAG --namespace=dev" 
    - name: Push image
      id: push
      run: |
        # push docker image to ECR
        docker push ${{ steps.build.outputs.image }}:${{steps.build.outputs.tag}}
        docker push ${{ steps.build.outputs.image }}:${{steps.build.outputs.latest}}
    # - name: Notify slack
    #   env:
    #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    #   uses: pullreminders/slack-action@master
    #   with:
    #     args: '{\"channel\":\"C015DEMCDK8\",\"text\":\"Application *hello-service* has been successfully built.\",\"attachments\":[{\"fields\":[{\"title\":\"Repo\",\"value\":\"${{ steps.git.outputs.repo }}\",\"short\":true},{\"title\":\"Branch\",\"value\":\"${{ steps.git.outputs.branch }}\",\"short\":true},{\"title\":\"Commit\",\"value\":\"${{ steps.git.outputs.commit }}\",\"short\":true},{\"title\":\"Image Tag\",\"value\":\"${{steps.build.outputs.tag}}\",\"short\":true},{\"title\":\"Deploy on Dev\",\"value\":\"```${{steps.build.outputs.deploy}}```\",\"short\":false}]}]}'        
    - name: Repository Dispatch
      if: github.ref == 'refs/heads/master'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.CI_TOKEN }}
        event-type: deploy
        client-payload: '{"service": "${{steps.build.outputs.service}}", "tag": "${{steps.build.outputs.tag}}"}'  