on:
  push:
    paths:
      - 'hello_service/**'
      - '!hello_service/k8s-hello-service/**'
      - '!hello_service/k8s-hello-service-external/**'
          
name: hello-service 
jobs:
  ci:
    runs-on: ubuntu-latest    
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.CI_TOKEN }}
    - name: Git info
      id: git
      run: |
        REPO=$(pwd | awk -F / '{print $(NF -1)}')
        BRANCH=$(git branch | grep \* | cut -d ' ' -f2)
        BRANCH_PREFIX=$(git branch | grep \* | cut -d ' ' -f2 | cut -d '/' -f1)
        COMMIT=$(git rev-parse --short HEAD)
        echo "::set-output name=repo::$REPO"
        echo "::set-output name=branch::$BRANCH"
        echo "::set-output name=prefix::$BRANCH_PREFIX"
        echo "::set-output name=commit::$COMMIT"                    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-2
    - name: Build image
      # we don't create a image for prod branch, we just promote the image.   
      if: ${{ steps.git.outputs.prefix }} != "prod"
      id: build
      env:
        SERVICE_NAME: hello-service 
        REPO: ${{ steps.git.outputs.repo }}
        BRANCH: ${{ steps.git.outputs.branch }}
        BRANCH_PREFIX: ${{ steps.git.outputs.prefix }}
        COMMIT: ${{ steps.git.outputs.commit }}
        ECR: ${{ steps.login-ecr.outputs.registry }}
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      run: |
       # Create a tag for docker image 
        if [[ $BRANCH_PREFIX != "master" ]]; then
          TAG=${BRANCH_PREFIX}-t$(date "+%F")-${{ steps.git.outputs.commit }}
          LATEST_TAG=${BRANCH_PREFIX}-latest
        else
          TAG=t$(date "+%F")-${{ steps.git.outputs.commit }}
          LATEST_TAG=latest  
        fi
        # Build a docker image
        docker build --no-cache --build-arg GITHUB_TOKEN  --build-arg REPO=${REPO} --build-arg BRANCH=${BRANCH} --build-arg COMMIT=${COMMIT} -t $ECR/$SERVICE_NAME:$LATEST_TAG \
                                              -t $ECR/$SERVICE_NAME:$TAG hello_service/.
        echo "::set-output name=tag::$TAG"
        echo "::set-output name=latest::$LATEST_TAG"
        echo "::set-output name=image::$ECR/$SERVICE_NAME" 
    - name: Push image
      id: push
      run: |
        # push docker image to ECR
        docker push ${{ steps.build.outputs.image }}:${{steps.build.outputs.tag}}
        docker push ${{ steps.build.outputs.image }}:${{steps.build.outputs.latest}}
    - name: Change the deployment tag on master
      if: github.ref == 'refs/heads/master'
      run: |
        #change the deployment tag on master
        sed -i 's/tag.*/tag: ${{steps.build.outputs.tag}}/g' hello_service/k8s-hello-service/values.yaml
        git status
        git add hello_service/k8s-hello-service/.
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Auto updating image tag:${{steps.build.outputs.tag}}"
    - name: Push changes to master
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.CI_TOKEN }}