name: DeployToProd
on: 
  workflow_dispatch:
    inputs:
      service:
        description: 'Service Name'     
        required: true
jobs:   
  PR:
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.CI_TOKEN }}
    - name: Connect to K8S
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
      with:
        args: |
          SHA=$(kubectl describe -n tools applications.argoproj.io qa-${{ github.event.inputs.service }} | grep service:t | cut -f7 -d "-")
          TAG=$(kubectl describe -n tools applications.argoproj.io qa-${{ github.event.inputs.service }} | grep service:t | cut -f2 -d ":")

          echo "::set-output name=sha::$SHA"
          echo "::set-output name=tag::$TAG"                
    - name: Create Branch
      run: |
        BRANCH=qa-${{ github.event.inputs.service }}-${{ steps.git.outputs.sha }}
        DIR=$(echo "${${{ github.event.inputs.service }}//-/_}")
        
        git checkout -b $BRANCH ${{ steps.git.outputs.sha }}
        sed -i 's/tag.*/tag: ${{ steps.git.outputs.tag }}/g' $DIR_service/k8s/values.yaml
        git status
        git add $DIR_service/k8s/.
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "promote ${{ github.event.inputs.service }}-service image to prod"
        git push --set-upstream origin $BRANCH

        echo "::set-output name=branch::$BRANCH"
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.CI_TOKEN }}
        commit-message: ${{ github.event.inputs.service }} to prod 
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: prod/$DIR_service
        delete-branch: true
        title: '${{ github.event.inputs.service }} to prod'
        labels: |
          api
          automated pr
        team-reviewers: |
          owners
          maintainers
        milestone: 1
        draft: false
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
