name: deploy-to-prod
on: 
  workflow_dispatch:
    inputs:
      service:
        description: 'Service Name'     
        required: true
jobs:   
  PR:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.CI_TOKEN }}
          fetch-depth: 0    
    - name: QA Deployment Image
      id: qa-image
      uses: Consensys/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
      with:
        args: get -n tools applications.argoproj.io qa-${{ github.event.inputs.service }}-service -o jsonpath="{..images}"
    - name: Prod Deployment Image
      id: prod-image
      uses: Consensys/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
      with:
        args: get -n tools applications.argoproj.io prod-${{ github.event.inputs.service }}-service -o jsonpath="{..images}"        
    - name: Create Variables
      if: ${{ steps.qa-image.outputs.result != steps.prod-image.outputs.result }}
      id: var
      run: |
        SHA=$(echo ${{ steps.qa-image.outputs.result }} | tr -d ] | cut -d "-" -f7)
        TAG=$(echo ${{ steps.qa-image.outputs.result }} | tr -d ] | cut -d ":" -f2)
        BRANCH=qa/${{ github.event.inputs.service }}-$SHA
        SDIR=$(echo "${{ github.event.inputs.service }}" | tr - _)_service
        echo "::set-output name=sha::$SHA"
        echo "::set-output name=tag::$TAG"
        echo "::set-output name=branch::$BRANCH"
        echo "::set-output name=dir::$SDIR"            
    - name: Create Branch
      id: branch
      run: |
        git branch ${{ steps.var.outputs.branch }} ${{ steps.var.outputs.sha }}
        git push --set-upstream origin ${{ steps.var.outputs.branch }}
    - name: Change the Tag  
      run: |
        git Checkout ${{ steps.var.outputs.branch }}
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        sed -i "s/tag.*/tag: ${{ steps.var.outputs.tag }}/g" ${{ steps.var.outputs.dir }}/k8s/values.yaml
        git add -A
        git commit -m "promote ${{ steps.var.outputs.tag }} to prod"
        git push --set-upstream origin ${{ steps.var.outputs.branch }}
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.CI_TOKEN }}
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        base: prod/${{ steps.var.outputs.dir }}
        branch: ${{ steps.var.outputs.branch }}
        delete-branch: true
        title: '${{ github.event.inputs.service }} to prod'
        body: |
          ${{ github.event.inputs.service }} to prod
          - Updated with *today's* date
          - Auto-generated by GitHub       
        labels: |
          api
          deploy
          automated pr
        team-reviewers: |
          owners
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
