name: DeployToProd
on: 
  workflow_dispatch:
    inputs:
      service:
        description: 'Service Name'     
        required: true
jobs:   
  PR:
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.CI_TOKEN }}
    - name: Deployment Image
      id: image
      uses: Consensys/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
      with:
        args: get -n tools applications.argoproj.io qa-${{ github.event.inputs.service }}-service -o jsonpath="{..images}"
    - name: Create Branch
      run: |
        SHA=$(echo ${{ steps.image.outputs.result }} | tr -d ] | cut -d "-" -f7)
        TAG=$(echo ${{ steps.image.outputs.result }} | tr -d ] | cut -d ":" -f2)
        BRANCH=qa/${{ github.event.inputs.service }}-$SHA
        DIR=$(echo "${${{ github.event.inputs.service }}//-/_}")
        
        git checkout -b $BRANCH $SHA
        sed -i 's/tag.*/tag: $TAG/g' $DIR_service/k8s/values.yaml
        git status
        git add $DIR_service/k8s/.
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "promote ${{ github.event.inputs.service }}-service image to prod"
        git push --set-upstream origin $BRANCH
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.CI_TOKEN }}
        commit-message: ${{ github.event.inputs.service }} to prod 
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: prod/$DIR_service
        delete-branch: true
        title: '${{ github.event.inputs.service }} to prod'
        labels: |
          api
          automated pr
        team-reviewers: |
          owners
          maintainers
        milestone: 1
        draft: false
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
